// =============================================
// SneakersInn — Central Configuration
// =============================================

export const CONFIG = {
    WHATSAPP_NUMBER: "233542630699",
    STORE_NAME: "𝚜𝚗𝚎𝚊𝚔𝚎𝚛𝚜𝙸𝚗𝚗",
    STORE_TAGLINE: "Step into your style",
    CURRENCY: "GH₵",
    SOCIAL: {
        instagram: "#",
        twitter: "#",
        tiktok: "#",
    },
    PIXEL_ID: "YOUR_PIXEL_ID", // Replace with actual ID
};

// =============================================
// Product Catalog
// =============================================

export const PRODUCTS = [
    {
        id: 1,
        name: "Nike SB Dunk Low Travis Scott",
        subtitle: "Velvet Brown",
        price: 350,
        category: "limited",
        image: "/images/nike-sb-travis-brown.png",
        sizes: [39, 40, 41, 42, 43, 44, 45],
        description:
            "The Nike SB Dunk Low Travis Scott in the coveted Velvet Brown colorway. Features rich suede and leather overlays with paisley bandana print accents. A true grail for any sneaker collector.",
        featured: true,
        badge: "🔥 Hot",
    },
    {
        id: 2,
        name: "New Balance 1906A",
        subtitle: "",
        price: 410,
        category: "running",
        image: "/images/nb-1906a.png",
        sizes: [39, 40, 41, 42, 43, 44, 45],
        description:
            "The New Balance 1906A combines retro runner aesthetics with modern comfort technology. A grey and silver colorway with mesh and leather construction for a premium look and feel.",
        featured: true,
        badge: "New",
    },
    {
        id: 3,
        name: "New Balance 1906R",
        subtitle: "",
        price: 450,
        category: "running",
        image: "/images/nb-1906r.png",
        sizes: [39, 40, 41, 42, 43, 44, 45],
        description:
            "The New Balance 1906R in a clean white and navy blue colorway. Retro running design with premium materials, N-ergy and ABZORB cushioning for ultimate comfort.",
        featured: false,
        badge: "",
    },
    {
        id: 4,
        name: "New Balance 1000",
        subtitle: "",
        price: 400,
        category: "running",
        image: "/images/nb-1000.png",
        sizes: [39, 40, 41, 42, 43, 44, 45],
        description:
            "The New Balance 1000 in a sleek black and grey colorway. Modern chunky design with mesh and suede upper. A bold silhouette that stands out on the streets.",
        featured: false,
        badge: "",
    },
    {
        id: 5,
        name: "Travis Scott Black Phantom",
        subtitle: "",
        price: 350,
        category: "limited",
        image: "/images/travis-scott-phantom.png",
        sizes: [39, 40, 41, 42, 43, 44, 45],
        description:
            "The Travis Scott x Jordan 1 Low OG Black Phantom. All-black premium leather with the signature reverse swoosh and contrast white stitching. Stealth mode activated.",
        featured: true,
        badge: "🔥 Hot",
    },
    {
        id: 6,
        name: "Air Force 1 Metro",
        subtitle: "Red",
        price: 450,
        category: "casual",
        image: "/images/airforce-metro-red.png",
        sizes: [39, 40, 41, 42, 43, 44, 45],
        description:
            "The Nike Air Force 1 Metro in a bold all-red leather upper paired with a crisp white sole. A head-turning statement piece for those who dare to stand out.",
        featured: true,
        badge: "Best Seller",
    },
    {
        id: 7,
        name: "Adidas Superstar Madness",
        subtitle: "",
        price: 370,
        category: "casual",
        image: "/images/adidas-superstar.png",
        sizes: [38, 39, 40, 41, 42, 43, 44, 45],
        description:
            "The iconic Adidas Superstar with a madness twist. Classic white leather upper with black shell toe and three stripes. A timeless design that never goes out of style.",
        featured: false,
        badge: "",
    },
    {
        id: 8,
        name: "Nike SB Dunk Low",
        subtitle: "Ash / Grey",
        price: 350,
        category: "casual",
        image: "/images/nike-sb-ash-grey.png",
        sizes: [39, 40, 41, 42, 43, 44, 45],
        description:
            "The Nike SB Dunk Low in a clean ash grey colorway. Premium suede and leather construction with a minimal design. Perfect for everyday wear with any outfit.",
        featured: false,
        badge: "",
    },
    {
        id: 9,
        name: "Dior Chrono",
        subtitle: "",
        price: 450,
        category: "limited",
        image: "/images/dior-chrono.png",
        sizes: [39, 40, 41, 42, 43, 44, 45],
        description:
            "The Dior Chrono — luxury meets athletic performance. White and grey with metallic silver accents and chunky sculpted sole. High-fashion streetwear at its finest.",
        featured: true,
        badge: "Luxury",
    },
    {
        id: 10,
        name: "Nike Air Max Drift",
        subtitle: "",
        price: 385,
        category: "running",
        image: "/images/air-max-drift.png",
        sizes: [39, 40, 41, 42, 43, 44, 45],
        description:
            "The Nike Air Max Drift in black and white. Featuring a visible Air unit for maximum cushioning and a modern running-inspired design built for all-day comfort.",
        featured: false,
        badge: "",
    },
    {
        id: 11,
        name: "Nike Air Max 95",
        subtitle: "",
        price: 380,
        category: "running",
        image: "/images/air-max-95.png",
        sizes: [39, 40, 41, 42, 43, 44, 45],
        description:
            "The legendary Nike Air Max 95 in the classic grey and neon yellow OG colorway. Layered panel design inspired by human anatomy with visible Air units in the heel and forefoot.",
        featured: true,
        badge: "Classic",
    },
    {
        id: 12,
        name: "Air Force 1 Low",
        subtitle: "White / Black",
        price: 300,
        category: "casual",
        image: "/images/af1-white-black.png",
        sizes: [38, 39, 40, 41, 42, 43, 44, 45, 46],
        description:
            "The essential Nike Air Force 1 Low in the clean white leather with black swoosh colorway. An everyday staple that pairs with everything. The most versatile sneaker in any rotation.",
        featured: false,
        badge: "",
    },
    {
        id: 13,
        name: "New Balance 9060",
        subtitle: "",
        price: 410,
        category: "running",
        image: "/images/nb-9060.png",
        sizes: [39, 40, 41, 42, 43, 44, 45],
        description:
            "The New Balance 9060 in a beautiful grey and cream colorway. Chunky modern runner design with ABZORB cushioning and suede overlays. The most hyped NB silhouette right now.",
        featured: true,
        badge: "Trending",
    },
    {
        id: 14,
        name: "Air Force 1 Foamposite",
        subtitle: "",
        price: 370,
        category: "limited",
        image: "/images/af1-foamposite.png",
        sizes: [39, 40, 41, 42, 43, 44, 45],
        description:
            "The Nike Air Force 1 Foamposite — where futurism meets classic. Iridescent holographic upper with a glossy finish that shifts color as you move. A true statement shoe.",
        featured: false,
        badge: "Futuristic",
    },
    {
        id: 15,
        name: "Air Jordan 4 Black Cat",
        subtitle: "Retro",
        price: 550,
        category: "limited",
        image: "/images/aj4-black-cat.png",
        sizes: [39, 40, 41, 42, 43, 44, 45],
        description:
            "The Air Jordan 4 Black Cat. All-black premium nubuck upper with matching hardware. The most requested Jordan 4 colorway ever. Stealthy, versatile, and iconic.",
        featured: true,
        badge: "Sold Out",
        soldOut: true,
    },
    {
        id: 16,
        name: "Yeezy Slide",
        subtitle: "Pure",
        price: 250,
        category: "casual",
        image: "/images/yeezy-slide-pure.png",
        sizes: [39, 40, 41, 42, 43, 44, 45],
        description:
            "The Adidas Yeezy Slide in Pure. Injected EVA foam for lightweight durability and soft top layer for immediate step-in comfort. The ultimate lounge footwear.",
        featured: true,
        badge: "Sold Out",
        soldOut: true,
    },
    {
        id: 17,
        name: "Nike Dunk Low",
        subtitle: "Panda",
        price: 300,
        category: "casual",
        image: "/images/dunk-low-panda.png",
        sizes: [38, 39, 40, 41, 42, 43, 44, 45],
        description:
            "The Nike Dunk Low Panda black and white. Smooth leather overlays in a classic two-tone colorblocking. The most popular sneaker on the streets for a reason.",
        featured: false,
        badge: "Restocking Soon",
        soldOut: true,
    },
    {
        id: 18,
        name: "Travis Scott x Jordan 1 Low",
        subtitle: "Olive",
        price: 850,
        category: "limited",
        image: "/images/travis-scott-olive.png",
        sizes: [39, 40, 41, 42, 43, 44, 45],
        description:
            "The Travis Scott x Air Jordan 1 Low Olive. Premium leather and suede upper with the oversized reverse swoosh in olive green. A grail-status collaboration.",
        featured: true,
        badge: "Sold Out",
        soldOut: true,
    },
    {
        id: 19,
        name: "Silver Cuban Link Chain",
        subtitle: "925 Sterling",
        price: 600,
        category: "accessories",
        image: "/images/jewellery-cuban.png",
        sizes: ["50cm", "55cm", "60cm"],
        description: "Premium 925 Sterling Silver Cuban Link Chain. Heavyweight feel, diamond-cut links for maximum shine. Tarnish-resistant and built to last.",
        featured: false,
        badge: "Dropping Soon",
        comingSoon: true,
    },
    {
        id: 20,
        name: "Signet Ring & Bracelet Set",
        subtitle: "Silver",
        price: 450,
        category: "accessories",
        image: "/images/jewellery-rings.png",
        sizes: ["S", "M", "L"],
        description: "Minimalist Signet Ring and matching Chain Bracelet set. The perfect finishing touch to any outfit. Clean, understated luxury.",
        featured: false,
        badge: "Dropping Soon",
        comingSoon: true,
    },
    {
        id: 21,
        name: "Heavyweight Tee",
        subtitle: "Midnight Black",
        price: 300,
        category: "apparel",
        image: "/images/tshirt-heavyweight-black.png",
        sizes: ["M", "L", "XL", "XXL"],
        description: "300gsm Heavyweight Cotton T-Shirt. Boxy fit, drop shoulders, and thick collar. The ultimate essential tee that keeps its shape.",
        featured: false,
        badge: "Dropping Soon",
        comingSoon: true,
    },
    {
        id: 22,
        name: "Earth Tone Tee Pack",
        subtitle: "3-Pack",
        price: 800,
        category: "apparel",
        image: "/images/tshirt-earth-stack.png",
        sizes: ["M", "L", "XL", "XXL"],
        description: "Essential 3-Pack in Olive, Beige, and Charcoal. Premium heavyweight cotton. Earth tones that pair perfectly with any sneaker rotation.",
        featured: false,
        badge: "Dropping Soon",
        comingSoon: true,
    },
    {
        id: 23,
        name: "New Balance 9060",
        subtitle: "Rain Cloud",
        price: 1200,
        category: "sneakers",
        image: "/images/nb-9060-rain-cloud.png",
        sizes: [40, 41, 42, 43, 44, 45],
        description: "The New Balance 9060 reinterprets familiar elements from the classic 99X series with a warped sensibility inspired by the futuristic, visible tech aesthetic of the Y2K era.",
        featured: false,
        badge: "Dropping Soon",
        comingSoon: true,
    },
    {
        id: 24,
        name: "Yeezy Foam Runner",
        subtitle: "Sand",
        price: 900,
        category: "sneakers",
        image: "/images/yeezy-foam-runner-sand.png",
        sizes: [40, 41, 42, 43, 44, 45],
        description: "The Yeezy Foam Runner features a unique foam compound that blends lightweight EVA with harvested algae. Neutral monochrome finish and sculpted lines.",
        featured: false,
        badge: "Dropping Soon",
        comingSoon: true,
    },
    {
        id: 25,
        name: "Fear of God Essentials Hoodie",
        subtitle: "Oatmeal",
        price: 850,
        category: "apparel",
        image: "/images/essentials-hoodie-oatmeal.png",
        sizes: ["S", "M", "L", "XL"],
        description: "The Jerry Lorenzo-designed hoodie in the classic Oatmeal colorway. Heavyweight fleece, rubberized logo on chest, and the signature oversized fit.",
        featured: false,
        badge: "Dropping Soon",
        comingSoon: true,
    },
    {
        id: 26,
        name: "Corteiz Guerillaz Cargos",
        subtitle: "Black / Yellow",
        price: 1100,
        category: "apparel",
        image: "/images/corteiz-cargos-black.png",
        sizes: ["S", "M", "L", "XL"],
        description: "Corteiz Guerillaz Cargos in Black. Featuring the iconic Alcatraz logo and multiple utility pockets. The street uniform of Accra.",
        featured: false,
        badge: "Dropping Soon",
        comingSoon: true,
    },
    {
        id: 27,
        name: "African Wolf Tooth Chain",
        subtitle: "Vintage Silver",
        price: 450,
        category: "accessories",
        image: "/images/wolf-tooth-chain.png",
        sizes: ["50cm"],
        description: "Vintage-inspired African Wolf Tooth pendant on a premium black braided cord. A bold statement piece connecting to heritage.",
        featured: false,
        badge: "Dropping Soon",
        comingSoon: true,
    },
    {
        id: 28,
        name: "Minimalist Band Ring",
        subtitle: "Matte Black",
        price: 250,
        category: "accessories",
        image: "/images/mens-band-ring.png",
        sizes: ["8", "9", "10", "11"],
        description: "Men's minimalist band ring in matte black tungsten. Scratch-resistant, durable, and understated. The perfect everyday accessory.",
        featured: false,
        badge: "Dropping Soon",
        comingSoon: true,
    },
    {
        id: 29,
        name: "Tribal Bead Stack",
        subtitle: "Earth Tones",
        price: 350,
        category: "accessories",
        image: "/images/mens-bead-leather-bracelet.png",
        sizes: ["Adjustable"],
        description: "Handcrafted stack of leather and bead bracelets in earth tones. Adds a rugged, traveled touch to any wrist game.",
        featured: false,
        badge: "Dropping Soon",
        comingSoon: true,
    },
];
